"use client";

import ReactMarkdown from "react-markdown";

interface PrintReportContentProps {
  reportText: string;
  purpose: string;
  createdAt: string;
}

export function PrintReportContent({
  reportText,
  purpose,
  createdAt,
}: PrintReportContentProps) {
  return (
    <main className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-8 py-12">
        <header className="mb-8 pb-4 border-b border-gray-200">
          <h1 className="text-2xl font-bold text-gray-900">診断レポート</h1>
          <p className="text-gray-600 mt-1">{purpose}</p>
          <p className="text-sm text-gray-400 mt-2">
            生成日: {new Date(createdAt).toLocaleDateString("ja-JP")}
          </p>
        </header>

        <article className="prose prose-sm max-w-none">
          <ReactMarkdown>{reportText}</ReactMarkdown>
        </article>

        <footer className="mt-12 pt-4 border-t border-gray-200 text-center text-sm text-gray-400 no-print">
          <button
            onClick={() => window.print()}
            className="px-4 py-2 bg-gray-100 rounded-lg hover:bg-gray-200 transition-colors"
          >
            印刷する
          </button>
        </footer>

        <footer className="print-only mt-12 pt-4 border-t border-gray-200 text-center text-sm text-gray-400">
          Generated by 倍速アンケート
        </footer>
      </div>
    </main>
  );
}
